/*
 * Copyright 2014-2015 Peng Wan <phylame@163.com>
 *
 * This file is part of Jem.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package pw.phylame.jem.formats.common;

import java.util.Map;
import java.util.zip.Deflater;

import pw.phylame.jem.formats.util.Versions;
import pw.phylame.jem.formats.util.config.ConfigUtils;
import pw.phylame.jem.formats.util.config.CommonConfig;
import pw.phylame.jem.formats.util.config.InvalidConfigException;

/**
 * Base config for ZIP e-book.
 */
public abstract class ZipMakerConfig implements CommonConfig {
    public static final String ZIP_METHOD = "zip.method";       // int
    public static final String ZIP_LEVEL = "zip.level";         // int
    public static final String ZIP_COMMENT = "zip.comment";     // String

    /**
     * Compression method of ZIP entry.
     */
    public int zipMethod = Deflater.DEFLATED;

    /**
     * Compression level of ZIP entry.
     */
    public int zipLevel = Deflater.DEFAULT_COMPRESSION;

    /**
     * Comment string for ZIP.
     */
    public String zipComment = "generated by Jem Formats v" + Versions.VERSION;

    @Override
    public void fetch(Map<String, Object> kw) throws InvalidConfigException {
        zipMethod = ConfigUtils.fetchInteger(kw, ZIP_METHOD, zipMethod);
        zipLevel = ConfigUtils.fetchInteger(kw, ZIP_LEVEL, zipLevel);
        zipComment = ConfigUtils.fetchString(kw, ZIP_COMMENT, zipComment);
    }
}
