/*
 * Copyright 2014-2015 Peng Wan <phylame@163.com>
 *
 * This file is part of Jem.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package pw.phylame.jem.formats.common;

import java.util.zip.Deflater;

import pw.phylame.jem.formats.util.Versions;
import pw.phylame.jem.formats.util.config.ConfigKey;
import pw.phylame.jem.formats.util.config.AbstractConfig;

/**
 * Base config for parsing e-book archived with ZIP.
 */
public abstract class ZipMakeConfig extends AbstractConfig {
    public static final String ZIP_METHOD = "zip.method";
    public static final String ZIP_LEVEL = "zip.level";
    public static final String ZIP_COMMENT = "zip.comment";

    /**
     * Compression method of ZIP entry.
     */
    @ConfigKey(ZIP_METHOD)
    public int zipMethod = Deflater.DEFLATED;

    /**
     * Compression level of ZIP entry.
     */
    @ConfigKey(ZIP_LEVEL)
    public int zipLevel = Deflater.DEFAULT_COMPRESSION;

    /**
     * Comment string for ZIP.
     */
    @ConfigKey(ZIP_COMMENT)
    public String zipComment = "Generated by Jem Formats v" + Versions.VERSION + '\n' + Versions.RIGHTS;
}
