/*
 * Copyright 2014-2015 Peng Wan <phylame@163.com>
 *
 * This file is part of Jem.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package pw.phylame.jem.formats.epub;

import pw.phylame.jem.core.Jem;

import pw.phylame.jem.formats.epub.html.StyleProvider;
import pw.phylame.jem.formats.epub.html.DefaultStyleProvider;

import java.util.zip.Deflater;

/**
 * Configuration for making ePub.
 */
public class EpubConfig {
    public String version = "2.0";

    // directory
    public String opsDir = "oebps";
    public String textDir = "text", imageDir = "images", styleDir = "styles";

    // common date format
    public String dateFormat = "yyyy-M-d";

    // XML style
    public String xmlEncoding = "UTF-8", xmlIndent = "\t", xmlLineSeparator =
            System.getProperty("line.separator");

    // encoding for html content
    public String htmlEncoding = "UTF-8";

    // indent for html content
    public String htmlIndent = "\t";

    public StyleProvider styleProvider = new DefaultStyleProvider();

    // ZIP compression
    public int zipMethod = Deflater.DEFLATED, zipLevel = Deflater.DEFAULT_COMPRESSION;

    // ZIP comment
    public String zipComment = "generated by jem " + Jem.VERSION;
}
